POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Cadu",
  "email": "carlos@email"
}

###
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "7637aa59-f257-4c50-af91-96b9bcd84c0b"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "7637aa59-f257-4c50-af91-96b9bcd84c0b",
    "account_id_to": "f22297c6-424f-4c4e-b32e-2eef3c6f8500",
    "amount": 1
}

###
GET http://localhost:8080/clients HTTP/1.1